### ISSUE TITLE
aprs.fi links broken for packets with callsigns that lack explicit APRS SSID

### ISSUE THREAD

**Issue by raphaelthomas** [hb9tf/statusupdater#2]
The following packet for example, which has been received by `HB9TF-1`, contains callsign `HB3XPA` that lacks an explicit SSID:
```2020-09-02 16:42:10.713 HB9TF-1   R HB3XPA>T7RRW9:`~=vl#/-\`"9<}HB9TF WORKSHOP ACTIVE_%```

StatusUpdater outputs the following (to Slack in this case), creating a broken link to aprs.fi due to the implicit assumption of SSID 0 (which is correct according to APRS spec I think):
```
StatusUpdaterAPP  18:42
HB3XPA via APRS: :house: In Service (0km/h, 20°) in Zürich CH (https://aprs.fi/HB3XPA-0)
```

**Comment by finfinack** [comment]
Indeed. Instead of trying to stringify the address ourselves:

https://github.com/hb9tf/statusupdater/blob/92d26b059274b2f794700acd800a4eb7ce1bc117/aprs/aprs.go#L117
https://github.com/hb9tf/statusupdater/blob/92d26b059274b2f794700acd800a4eb7ce1bc117/aprs/aprs.go#L122

We should actually just use the stingifier in the `go-aprs` library's `address.go`:

https://github.com/hb9tf/go-aprs/blob/fec063fe4427c98f05a284b7a0acad5771bc35d3/address.go#L20

I've fixed and verified it locally and will send a fix in a bit.

**Comment by finfinack** [comment]
This should now be fixed with https://github.com/hb9tf/statusupdater/commit/a1b3d2c3fb039c7e6c77bcd2b7aeb4e4073fe2fb
